version: "3.3"

services:
  chat_database:
    container_name: database
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=chat
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
